# Stdlib imports
import os

CONTEXT_API_USERNAME = os.environ.get("NEWSAI_CONTEXT_API_USERNAME")
CONTEXT_API_PASSWORD = os.environ.get("NEWSAI_CONTEXT_API_PASSWORD")
ELASTICSEARCH_USER = os.environ.get("NEWSAI_ELASTICSEARCH_USER")
ELASTICSEARCH_PASSWORD = os.environ.get("NEWSAI_ELASTICSEARCH_PASSWORD")
